.PHONY: clean All

All:
	@echo "----------Building project:[ Huawei-LiteOS - BuildSet ]----------"
	@cd "F:\CK\LiteOS\targets\Cloud_CB2201\cdk" && make -f  "Huawei-LiteOS.mk" && make -f  "Huawei-LiteOS.mk" PostBuild
clean:
	@echo "----------Cleaning project:[ Huawei-LiteOS - BuildSet ]----------"
	@cd "F:\CK\LiteOS\targets\Cloud_CB2201\cdk" && make -f  "Huawei-LiteOS.mk" clean
