DIRECTORIES += platform/MM32L073PF

C_SOURCES += platform/MM32L073PF/los_bsp_adapter.c  \
			 platform/MM32L073PF/los_bsp_key.c  \
			 platform/MM32L073PF/los_bsp_led.c  \
			 platform/MM32L073PF/los_bsp_uart.c
			 

ASM_SOURCES += platform/MM32L073PF/los_startup_gcc.s
             
