DIRECTORIES += kernel/cpu/arm/cortex-m3

C_SOURCES += kernel/cpu/arm/cortex-m3/los_hw.c  \
             kernel/cpu/arm/cortex-m3/los_hw_tick.c  \
             kernel/cpu/arm/cortex-m3/los_hwi.c
			 

ASM_SOURCES += kernel/cpu/arm/cortex-m3/los_dispatch_gcc.s
