include hal/NUC472_442/Makefile
DEFINES += -DLOS_NUC472H
DIRECTORIES += platform/NUTINY-NUC472H

C_SOURCES += platform/NUTINY-NUC472H/los_bsp_adapter.c  \
			 platform/NUTINY-NUC472H/los_bsp_key.c  \
			 platform/NUTINY-NUC472H/los_bsp_led.c  \
			 platform/NUTINY-NUC472H/los_bsp_uart.c
			 

ASM_SOURCES += platform/NUTINY-NUC472H/los_startup_gcc.s
             
