DIRECTORIES += platform/NRF52840-PDK/nRF52840_xxAA

INCLUDES += "-Iplatform/NRF52840-PDK/config"
INCLUDES += "-Iplatform/NRF52840-PDK/components/drivers_nrf/hal"
INCLUDES += "-Iplatform/NRF52840-PDK/components/libraries/util"
INCLUDES += "-Iplatform/NRF52840-PDK/components/drivers_nrf/nrf_soc_nosd"

C_SOURCES += platform/NRF52840-PDK/nRF52840_xxAA/system_nrf52840.c

