DIRECTORIES += platform/LAUNCHXL-CC3220SF

C_SOURCES += platform/LAUNCHXL-CC3220SF/los_bsp_adapter.c  \
			 platform/LAUNCHXL-CC3220SF/los_bsp_key.c  \
			 platform/LAUNCHXL-CC3220SF/los_bsp_led.c  \
			 platform/LAUNCHXL-CC3220SF/los_bsp_uart.c
			 

ASM_SOURCES += platform/LAUNCHXL-CC3220SF/los_startup_gcc.s
             
