include platform/NRF52840-PDK/nRF52840_xxAA/Makefile
DIRECTORIES += platform/NRF52840-PDK
DEFINES += -DLOS_NRF52840 -DNRF52840_XXAA -DCONFIG_GPIO_AS_PINRESET

C_SOURCES += platform/NRF52840-PDK/los_bsp_adapter.c  \
			 platform/NRF52840-PDK/los_bsp_key.c  \
			 platform/NRF52840-PDK/los_bsp_led.c  \
			 platform/NRF52840-PDK/los_bsp_uart.c
			 

ASM_SOURCES += platform/NRF52840-PDK/los_startup_gcc.s
             
