include platform/NRF52-DK/Library/Makefile
DIRECTORIES += platform/NRF52-DK
DEFINES += -DNRF52832_XXAA

C_SOURCES += platform/NRF52-DK/los_bsp_adapter.c  \
			 platform/NRF52-DK/los_bsp_key.c  \
			 platform/NRF52-DK/los_bsp_led.c  \
			 platform/NRF52-DK/los_bsp_uart.c \
			 platform/NRF52-DK/system_nrf52.c \
			 

ASM_SOURCES += platform/NRF52-DK/los_startup_gcc.s
             
