DIRECTORIES += platform/EFM32-STK3700

C_SOURCES += platform/EFM32-STK3700/los_bsp_adapter.c  \
			 platform/EFM32-STK3700/los_bsp_key.c  \
			 platform/EFM32-STK3700/los_bsp_led.c  \
			 platform/EFM32-STK3700/los_bsp_uart.c
			 

ASM_SOURCES += platform/EFM32-STK3700/los_startup_gcc.s
             
