DIRECTORIES += platform/ATSAME70Q21

C_SOURCES += platform/ATSAME70Q21/los_bsp_adapter.c  \
			 platform/ATSAME70Q21/los_bsp_key.c  \
			 platform/ATSAME70Q21/los_bsp_led.c  \
			 platform/ATSAME70Q21/los_bsp_uart.c
			 

ASM_SOURCES += platform/ATSAME70Q21/los_startup_gcc.s
             
