include hal/STM32F4xx/Makefile
DEFINES += -DLOS_STM32F412Zx -DSTM32F412Zx 
DIRECTORIES += platform/STM32F412ZG-NUCLEO

C_SOURCES += platform/STM32F412ZG-NUCLEO/los_bsp_adapter.c  \
			 platform/STM32F412ZG-NUCLEO/los_bsp_key.c  \
			 platform/STM32F412ZG-NUCLEO/los_bsp_led.c  \
			 platform/STM32F412ZG-NUCLEO/los_bsp_uart.c \
			 platform/STM32F412ZG-NUCLEO/stm32f4xx_nucleo_144.c 

ASM_SOURCES += platform/STM32F412ZG-NUCLEO/los_startup_gcc.s
             
