DIRECTORIES += platform/MM32F103_MINI

C_SOURCES += platform/MM32F103_MINI/los_bsp_adapter.c  \
             platform/MM32F103_MINI/los_bsp_flash.c  \
			 platform/MM32F103_MINI/los_bsp_key.c  \
			 platform/MM32F103_MINI/los_bsp_led.c  \
			 platform/MM32F103_MINI/los_bsp_uart.c
			 

ASM_SOURCES += platform/MM32F103_MINI/los_startup_gcc.s
             
