DIRECTORIES += platform/M2S150_RV32

C_SOURCES += platform/M2S150_RV32/los_bsp_adapter.c  \
	     platform/M2S150_RV32/los_bsp_key.c  \
       	     platform/M2S150_RV32/los_bsp_led.c  \
             platform/M2S150_RV32/los_bsp_uart.c \
             platform/M2S150_RV32/CoreGPIO/core_gpio.c \
             platform/M2S150_RV32/CoreUARTapb/core_uart_apb.c \
             platform/M2S150_RV32/hal/hal_irq.c \
             platform/M2S150_RV32/hal/hw_reg_access.c \
             platform/M2S150_RV32/riscv_hal/init.c \
             platform/M2S150_RV32/riscv_hal/riscv_hal.c \
             platform/M2S150_RV32/riscv_hal/riscv_hal_stubs.c \
             platform/M2S150_RV32/riscv_hal/syscall.c 
			 

ASM_SOURCES += platform/M2S150_RV32/riscv_hal/entry.s
