#ifndef __CSI_CONFIG_H__
#define __CSI_CONFIG_H__
#define CONFIG_SYSTEM_SECURE 1
#define CONFIG_CHIP_CH2201 1
#define CONFIG_KERNEL_NONE 1
#define CONFIG_HAVE_VIC 1
#define CONFIG_ARCH_INTERRUPTSTACK 4096
#endif
