include ${SOURCE_ROOT}/kernel/base/Makefile
ifeq (${ARCH}, arm)
include ${SOURCE_ROOT}/kernel/cmsis/Makefile
endif
include ${SOURCE_ROOT}/kernel/config/Makefile
include ${SOURCE_ROOT}/kernel/cpu/${ARCH}/${CPU}/Makefile

C_SOURCES += 
