

include ${SOURCE_ROOT}/kernel/base/Makefile
include ${SOURCE_ROOT}/kernel/cmsis/Makefile
include ${SOURCE_ROOT}/kernel/config/Makefile
include ${SOURCE_ROOT}/kernel/cpu/${ARCH}/${CPU}/Makefile

C_SOURCES += 
