include hal/NANO100BN/Makefile

DEFINES += -DRAM_SIZE_LEVEL_0
DIRECTORIES += platform/NuTiny-Nano130K

C_SOURCES += platform/NuTiny-Nano130K/los_bsp_adapter.c  \
			 platform/NuTiny-Nano130K/los_bsp_key.c  \
			 platform/NuTiny-Nano130K/los_bsp_led.c  \
			 platform/NuTiny-Nano130K/los_bsp_uart.c

ASM_SOURCES += platform/NuTiny-Nano130K/los_startup_gcc.s
             
