DIRECTORIES += kernel/base/mem

C_SOURCES += kernel/base/mem/los_membox.c    \
             kernel/base/mem/los_memory.c    \
			 kernel/base/mem/los_memstat.c    \
			 kernel/base/mem/los_multipledlinkhead.c    