DIRECTORIES += hal/GD32F4xx

INCLUDES += "-Ihal/GD32F4xx/Include"
INCLUDES += "-Ithirdparty/FatFS/src"

C_SOURCES += hal/GD32F4xx/CMSIS/system_gd32f4xx.c  \
				hal/GD32F4xx/FWlib/gd32f4xx_exti.c \
				hal/GD32F4xx/FWlib/gd32f4xx_gpio.c \
				hal/GD32F4xx/FWlib/gd32f4xx_misc.c \
				hal/GD32F4xx/FWlib/gd32f4xx_rcu.c \
				hal/GD32F4xx/FWlib/gd32f4xx_syscfg.c \
				hal/GD32F4xx/FWlib/gd32f4xx_usart.c \
				hal/GD32F4xx/FWlib/systick.c