DIRECTORIES += kernel/cpu/riscv/rv32im

C_SOURCES += kernel/cpu/riscv/rv32im/los_hw.c  \
             kernel/cpu/riscv/rv32im/los_hw_tick.c  \
             kernel/cpu/riscv/rv32im/los_hwi.c
			 

ASM_SOURCES += kernel/cpu/riscv/rv32im/los_dispatch_gcc.s
