include hal/STM32F4xx/Makefile
DEFINES += -DLOS_STM32F429ZI -DSTM32F429xx
DIRECTORIES += platform/STM32F429I-DISCOVERY

C_SOURCES += platform/STM32F429I_DISCO/los_bsp_adapter.c  \
			 platform/STM32F429I_DISCO/los_bsp_key.c  \
			 platform/STM32F429I_DISCO/los_bsp_led.c  \
			 platform/STM32F429I_DISCO/los_bsp_uart.c \
			 platform/STM32F429I_DISCO/stm32f429i_discovery.c 
			 

ASM_SOURCES += platform/STM32F429I_DISCO/los_startup_gcc.s
             
