DIRECTORIES += platform/EFM32-SLSTK3401A

C_SOURCES += platform/EFM32-SLSTK3401A/los_bsp_adapter.c  \
			 platform/EFM32-SLSTK3401A/los_bsp_key.c  \
			 platform/EFM32-SLSTK3401A/los_bsp_led.c  \
			 platform/EFM32-SLSTK3401A/los_bsp_uart.c
			 

ASM_SOURCES += platform/EFM32-SLSTK3401A/los_startup_gcc.s
             
