DIRECTORIES += hal/STM32F7xx

INCLUDES += "-Ihal/STM32F7xx/Include"
INCLUDES += "-Ithirdparty/FatFS/src"

C_SOURCES += hal/STM32F7xx/CMSIS/system_stm32f7xx.c  \
				hal/STM32F7xx/FWlib/stm32f7xx_hal_gpio.c \
				hal/STM32F7xx/FWlib/stm32f7xx_hal_cortex.c \
				hal/STM32F7xx/FWlib/stm32f7xx_hal_rcc.c \
				hal/STM32F7xx/FWlib/stm32f7xx_hal_rcc_ex.c \
				hal/STM32F7xx/FWlib/stm32f7xx_hal.c \
				hal/STM32F7xx/FWlib/stm32f7xx_hal_uart.c \
				hal/STM32F7xx/FWlib/stm32f7xx_hal_dma.c