include $(LITEOSTOPDIR)/config.mk

MODULE_NAME := $(notdir $(CURDIR))

LOCAL_SRCS_y := nb_demo.c

LOCAL_INCLUDE := -I $(LITEOSTOPDIR)/include

LOCAL_SRCS := $(LOCAL_SRCS_y)
LOCAL_FLAGS := $(LOCAL_INCLUDE)

include $(MODULE)
