DIRECTORIES += hal/GD32F20x

INCLUDES += "-Ihal/GD32F20x/Include"
INCLUDES += "-Ithirdparty/FatFS/src"

C_SOURCES += hal/GD32F20x/CMSIS/system_gd32f20x.c  \
				hal/GD32F20x/FWlib/gd32f20x_exti.c \
				hal/GD32F20x/FWlib/gd32f20x_gpio.c \
				hal/GD32F20x/FWlib/gd32f20x_rcu.c \
				hal/GD32F20x/FWlib/gd32f20x_rtc.c \
				hal/GD32F20x/FWlib/gd32f20x_timer.c \
				hal/GD32F20x/FWlib/gd32f20x_usart.c