DIRECTORIES += hal/GD32F1x0

INCLUDES += "-Ihal/GD32F1x0/Include"
INCLUDES += "-Ithirdparty/FatFS/src"

C_SOURCES += hal/GD32F1x0/CMSIS/system_gd32f1x0.c  \
				hal/GD32F1x0/FWlib/gd32f1x0_exti.c \
				hal/GD32F1x0/FWlib/gd32f1x0_gpio.c \
				hal/GD32F1x0/FWlib/gd32f1x0_misc.c \
				hal/GD32F1x0/FWlib/gd32f1x0_rcu.c \
				hal/GD32F1x0/FWlib/gd32f1x0_syscfg.c \
				hal/GD32F1x0/FWlib/gd32f1x0_usart.c \
				hal/GD32F1x0/FWlib/systick.c