DIRECTORIES += hal/STM32L4xx

INCLUDES += "-Ihal/STM32L4xx/Include"
INCLUDES += "-Ithirdparty/FatFS/src"

C_SOURCES += hal/STM32L4xx/CMSIS/system_stm32l4xx.c  \
				hal/STM32L4xx/FWlib/stm32l4xx_hal.c \
				hal/STM32L4xx/FWlib/stm32l4xx_hal_cortex.c \
				hal/STM32L4xx/FWlib/stm32l4xx_hal_dma.c \
				hal/STM32L4xx/FWlib/stm32l4xx_hal_flash.c \
				hal/STM32L4xx/FWlib/stm32l4xx_hal_flash_ex.c \
				hal/STM32L4xx/FWlib/stm32l4xx_hal_gpio.c \
				hal/STM32L4xx/FWlib/stm32l4xx_hal_pwr.c \
				hal/STM32L4xx/FWlib/stm32l4xx_hal_pwr_ex.c \
				hal/STM32L4xx/FWlib/stm32l4xx_hal_rcc.c \
				hal/STM32L4xx/FWlib/stm32l4xx_hal_rcc_ex.c \
				hal/STM32L4xx/FWlib/stm32l4xx_hal_uart.c \
				hal/STM32L4xx/FWlib/stm32l4xx_hal_uart_ex.c \
				hal/STM32L4xx/FWlib/stm32l4xx_hal_usart.c