include hal/STM32F4xx/Makefile
DEFINES += -DLOS_STM32F411RE -DSTM32F411xE 
DIRECTORIES += platform/STM32F411RE-NUCLEO

C_SOURCES += platform/STM32F411RE-NUCLEO/los_bsp_adapter.c  \
			 platform/STM32F411RE-NUCLEO/los_bsp_key.c  \
			 platform/STM32F411RE-NUCLEO/los_bsp_led.c  \
			 platform/STM32F411RE-NUCLEO/los_bsp_uart.c	\
			 platform/STM32F411RE-NUCLEO/stm32f4xx_nucleo.c
			 

ASM_SOURCES += platform/STM32F411RE-NUCLEO/los_startup_gcc.s
             
