include platform/STM32F103RB-NUCLEO/Libraries/Makefile
DEFINES += -DSTM32F10X_MD -DUSE_STDPERIPH_DRIVER -DLOS_STM32F103RB -DRAM_SIZE_LEVEL_0
DIRECTORIES += platform/STM32F103RB-NUCLEO

C_SOURCES += platform/STM32F103RB-NUCLEO/los_bsp_adapter.c  \
			 platform/STM32F103RB-NUCLEO/los_bsp_key.c  \
			 platform/STM32F103RB-NUCLEO/los_bsp_led.c  \
			 platform/STM32F103RB-NUCLEO/los_bsp_uart.c
			 

ASM_SOURCES += platform/STM32F103RB-NUCLEO/los_startup_gcc.s
             
