DIRECTORIES += platform/LPC824_LITE

C_SOURCES += platform/LPC824_LITE/los_bsp_adapter.c  \
             platform/LPC824_LITE/los_bsp_flash.c  \
			 platform/LPC824_LITE/los_bsp_key.c  \
			 platform/LPC824_LITE/los_bsp_led.c  \
			 platform/LPC824_LITE/los_bsp_uart.c
			 

ASM_SOURCES += platform/LPC824_LITE/los_startup_gcc.s
             
