DIRECTORIES += platform/STM32F746ZG_NUCLEO

C_SOURCES += platform/STM32F746ZG_NUCLEO/los_bsp_adapter.c  \
			 platform/STM32F746ZG_NUCLEO/los_bsp_key.c  \
			 platform/STM32F746ZG_NUCLEO/los_bsp_led.c  \
			 platform/STM32F746ZG_NUCLEO/los_bsp_uart.c
			 

ASM_SOURCES += platform/STM32F429I_DISCO/los_startup_gcc.s
             
