include hal/STM32F7xx/Makefile
DEFINES += -DLOS_STM32F746ZG -DSTM32F746xx 
DIRECTORIES += platform/STM32F746ZG_NUCLEO

C_SOURCES += platform/STM32F746ZG_NUCLEO/los_bsp_adapter.c  \
			 platform/STM32F746ZG_NUCLEO/los_bsp_key.c  \
			 platform/STM32F746ZG_NUCLEO/los_bsp_led.c  \
			 platform/STM32F746ZG_NUCLEO/los_bsp_uart.c \
			 platform/STM32F746ZG_NUCLEO/stm32f7xx_nucleo_144.c
			 

ASM_SOURCES += platform/STM32F746ZG_NUCLEO/los_startup_gcc.s
             
