DIRECTORIES += hal/GD32F10x

INCLUDES += "-Ihal/GD32F10x/Include"
INCLUDES += "-Ithirdparty/FatFS/src"

C_SOURCES += hal/GD32F10x/CMSIS/system_gd32f10x.c  \
				hal/GD32F10x/FWlib/gd32f10x_exti.c \
				hal/GD32F10x/FWlib/gd32f10x_gpio.c \
				hal/GD32F10x/FWlib/gd32f10x_rcc.c \
				hal/GD32F10x/FWlib/gd32f10x_timer.c \
				hal/GD32F10x/FWlib/gd32f10x_usart.c