DIRECTORIES += kernel/cpu/arm/cortex-m0plus

C_SOURCES += kernel/cpu/arm/cortex-m0plus/los_hw.c  \
             kernel/cpu/arm/cortex-m0plus/los_hw_tick.c  \
             kernel/cpu/arm/cortex-m0plus/los_hwi.c
			 

ASM_SOURCES += kernel/cpu/arm/cortex-m0plus/los_dispatch_gcc.s
