DIRECTORIES += example/api

C_SOURCES += example/api/los_api_dynamic_mem.c  \
             example/api/los_api_event.c  \
             example/api/los_api_interrupt.c  \
             example/api/los_api_list.c  \
             example/api/los_api_msgqueue.c  \
             example/api/los_api_mutex.c  \
             example/api/los_api_sem.c  \
             example/api/los_api_static_mem.c  \
             example/api/los_api_systick.c  \
             example/api/los_api_task.c  \
             example/api/los_api_timer.c  \
             example/api/los_demo_entry.c  \
             example/api/los_inspect_entry.c 
			 
