

include ${SOURCE_ROOT}/kernel/base/core/Makefile
#include ${SOURCE_ROOT}/kernel/base/fs/Makefile
include ${SOURCE_ROOT}/kernel/base/ipc/Makefile
include ${SOURCE_ROOT}/kernel/base/mem/Makefile
include ${SOURCE_ROOT}/kernel/base/misc/Makefile



C_SOURCES += 
