DIRECTORIES += platform/FRDM-KL26Z

C_SOURCES += platform/FRDM-KL26Z/los_bsp_adapter.c  \
			 platform/FRDM-KL26Z/los_bsp_key.c  \
			 platform/FRDM-KL26Z/los_bsp_led.c  \
			 platform/FRDM-KL26Z/los_bsp_uart.c
			 

ASM_SOURCES += platform/FRDM-KL26Z/los_startup_gcc.s
             
