DIRECTORIES += platform/STM32F103ZE-ISO

C_SOURCES += platform/STM32F103ZE-ISO/los_bsp_adapter.c  \
			 platform/STM32F103ZE-ISO/los_bsp_key.c  \
			 platform/STM32F103ZE-ISO/los_bsp_led.c  \
			 platform/STM32F103ZE-ISO/los_bsp_uart.c \
			 platform/STM32F103ZE-ISO/Libraries/FWlib/src/stm32f10x_gpio.c \
			 platform/STM32F103ZE-ISO/Libraries/FWlib/src/stm32f10x_rcc.c \
			 platform/STM32F103ZE-ISO/Libraries/FWlib/src/stm32f10x_usart.c


ASM_SOURCES += platform/STM32F429I_DISCO/los_startup_gcc.s
             
