DIRECTORIES += platform/nRF51822

C_SOURCES += platform/nRF51822/los_bsp_adapter.c  \
			 platform/nRF51822/los_bsp_key.c  \
			 platform/nRF51822/los_bsp_led.c  \
			 platform/nRF51822/los_bsp_uart.c
			 

ASM_SOURCES += platform/nRF51822/los_startup_gcc.s
             
