include $(LITEOSTOPDIR)/config.mk

MODULE_NAME := csysdeps

LOCAL_INCLUDE :=

LOCAL_SRCS := memset.S strcmp.S setjmp.S memcpy.S

LOCAL_ASFLAGS := $(AS_OBJS_LIBC_FLAGS)

LOCAL_FLAGS := $(LOCAL_INCLUDE)

include $(MODULE_LIB)
