DIRECTORIES += platform/MM32L373

C_SOURCES += platform/MM32L373/los_bsp_adapter.c  \
			 platform/MM32L373/los_bsp_flash.c  \
			 platform/MM32L373/los_bsp_key.c  \
			 platform/MM32L373/los_bsp_led.c  \
			 platform/MM32L373/los_bsp_uart.c
			 

ASM_SOURCES += platform/MM32L373/los_startup_gcc.s
             
