# A Makefile for demo

include $(LITEOSTOPDIR)/config.mk

MODULE_NAME := $(DEMOS_EXAMPLE)

MODULE_$(LOSCFG_DEMOS_FS) += fs
MODULE_$(LOSCFG_DEMOS_GUI) += gui
MODULE_$(LOSCFG_DEMOS_SENSORHUB) += sensorhub

include $(MODULE)
