DIRECTORIES += kernel/base/core

C_SOURCES += kernel/base/core/los_priqueue.c \
             kernel/base/core/los_swtmr.c \
			 kernel/base/core/los_sys.c \
			 kernel/base/core/los_task.c \
			 kernel/base/core/los_tick.c \
			 kernel/base/core/los_timeslice.c 
