DIRECTORIES += platform/GD32F103VCT6

C_SOURCES += platform/GD32F103VCT6/los_bsp_adapter.c  \
			 platform/GD32F103VCT6/los_bsp_flash.c  \
			 platform/GD32F103VCT6/los_bsp_key.c  \
			 platform/GD32F103VCT6/los_bsp_led.c  \
			 platform/GD32F103VCT6/los_bsp_uart.c
			 

ASM_SOURCES += platform/GD32F103VCT6/los_startup_gcc.s
             
