DIRECTORIES += hal/STM32F4xx

INCLUDES += "-Ihal/STM32F4xx/Include"
INCLUDES += "-Ithirdparty/FatFS/src"

C_SOURCES += hal/STM32F4xx/CMSIS/system_stm32f4xx.c  \
				hal/STM32F4xx/FWlib/stm32f4xx_hal_gpio.c \
				hal/STM32F4xx/FWlib/stm32f4xx_hal_cortex.c \
				hal/STM32F4xx/FWlib/stm32f4xx_hal_rcc_ex.c \
				hal/STM32F4xx/FWlib/stm32f4xx_hal.c \
				hal/STM32F4xx/FWlib/stm32f4xx_hal_pwr.c \
				hal/STM32F4xx/FWlib/stm32f4xx_hal_rcc.c \
				hal/STM32F4xx/FWlib/stm32f4xx_hal_pwr_ex.c \
				hal/STM32F4xx/FWlib/stm32f4xx_hal_uart.c \
				hal/STM32F4xx/FWlib/stm32f4xx_hal_usart.c \
				hal/STM32F4xx/FWlib/stm32f4xx_hal_dma.c \
				hal/STM32F4xx/FWlib/stm32f4xx_hal_flash.c \
				hal/STM32F4xx/FWlib/stm32f4xx_hal_flash_ex.c \
				hal/STM32F4xx/FWlib/stm32f4xx_hal_i2c.c \
				hal/STM32F4xx/FWlib/stm32f4xx_hal_spi.c \
				hal/STM32F4xx/FWlib/stm32f4xx_hal_adc.c \
				hal/STM32F4xx/FWlib/stm32f4xx_hal_adc_ex.c