DIRECTORIES += platform/LPC54110_BOARD

C_SOURCES += platform/LPC54110_BOARD/los_bsp_adapter.c  \
             platform/LPC54110_BOARD/los_bsp_flash.c  \
			 platform/LPC54110_BOARD/los_bsp_key.c  \
			 platform/LPC54110_BOARD/los_bsp_led.c  \
			 platform/LPC54110_BOARD/los_bsp_uart.c
			 

ASM_SOURCES += platform/LPC54110_BOARD/los_startup_gcc.s
             
